### ISSUE TITLE
Version 2.3

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#11]
The new version does not change the values once loaded

all overlays stays the same and no cpu/clock speed and black screen exiting games.

i'm on 4.88 evilnat

**Comment by LuanTeles** [comment]
After a couple of reboots now its working LOL

**Comment by LuanTeles** [comment]
I rebooted my console now the clocks are gone o.O

**Comment by TheRouletteBoi** [comment]
> I rebooted my console now the clocks are gone o.O

try the new version. I updated the sprx in releases

**Comment by LuanTeles** [comment]
> > I rebooted my console now the clocks are gone o.O
> 
> try the new version. I updated the sprx in releases

I updated but no clock speeds.

**Comment by LuanTeles** [comment]
lol i rebooted again and :

![image](https://user-images.githubusercontent.com/74815634/163669810-e89ebed4-5e6e-4e9f-9819-21ab27f8f1a2.png)

**Comment by LuanTeles** [comment]
again

![image](https://user-images.githubusercontent.com/74815634/163671936-ab081f98-768f-4892-bca5-0bf3c099ac2e.png)

**Comment by TheRouletteBoi** [comment]
See issue #14 for fixes
