### ISSUE TITLE
[IDEA] Ram UsaGe

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#12]
As v2.3 shows ram usage in MB, I suggest  to automatically switch from MB to KB , just like the temperature that automatically switches from C to F.

BTW looks like it became inaccurate, when it was in KB, the memory usage was between 91-92% now in MB is 89.4%

**Comment by TheRouletteBoi** [comment]
I will not add this request but I will fix the accuracy
