### ISSUE TITLE
Idea to reduce text information + Bug report: Slash on PSX games 

### ISSUE THREAD

**Issue by aldostools** [TheRouletteBoi/RouLetteVshMenu#15]
I understand that the text labels are important for easy understanding of the information.

My concern is that since 2.3 there is too much static information taking too much space on screen.

My proposed solution is to show only the clock speeds without labels.
![image](https://user-images.githubusercontent.com/974897/165648855-3d779357-19e2-4b22-915e-58bf6c6f569c.png)
BTW The CPU/GPU labels for temperatures act as labels for the clock speeds too.

The user just need to read the documentation to interpret the meaning of the 3 values.
<hr>
On PSX games, there is a slash under the firmware version. That occurs because you show Title / Game ID.
An easy fix is to replace the slash with a space to show: Title   Game ID

**Comment by TheRouletteBoi** [comment]
you suggestion is nice and clean but I feel like the labels are important to know what the information means

**Comment by TheRouletteBoi** [comment]
![2022-05-06_16-27-32](https://user-images.githubusercontent.com/9206290/167228680-3b54aa24-553d-4e7a-a968-f77965b8c577.jpg)

what do you think about this layout? let me know if there should be any changes

**Comment by aldostools** [comment]
It is much better than the current layout that is full of text.

I prefer the layout without the labels in the clock speeds.

The intention is to reduce the amount of text. Both layouts are valid. You can update with the one that you prefer.

**Comment by TheRouletteBoi** [comment]
do you know where I could find CPU or GPU utilization?  and would it require hijacking LV1 threads?

**Comment by aldostools** [comment]
Sorry, I don't know where it's found. Maybe zecoxao, mysis or 3141card could know.
You may find them on twitter or PSX-PLACE forum.
