### ISSUE TITLE
CEX options

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#2]
I think your vsh menu needs to have two versions or two menus CEX and DEX, needing to click one by one to know if it runs in CEX is kinda annoying.

**Comment by TheRouletteBoi** [comment]
The reason why some menus are DEX only is that the original developers of the menus/sprx were made with DEX system calls, and the only way to change that is by having the source code to those menus. I only have access to the compiled binaries

**Comment by LuanTeles** [comment]
Can at least a text be added to the name of it, to easy identify for witH mode it runs? like BLABLAMENU (DEX) BLABLA (CEX)
(
