### ISSUE TITLE
Clock speeds are cleared when CFW Syscalls are disabled

### ISSUE THREAD

**Issue by aldostools** [TheRouletteBoi/RouLetteVshMenu#22]
The clock speeds for CPU/GPU already found, stop displaying when CFW Syscalls are disabled.

If the CFW Syscalls are restored, they appear again. Is this behavior intentional?

**Comment by TheRouletteBoi** [comment]
This behavior is intentional

**Comment by aldostools** [comment]
Ok. Then I'm closing the issue.
