### ISSUE TITLE
[Bug] CPU/GPU Information

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#23]
Seems like the settings below:
 
showCpuInfo: Off
showGpuInfo: Off

only works if the clock speeds are enabled, otherwise it will show the compact mode that can't be configurable.

BTW i loved the idea of keeping the compact mode if the clock speeds are disabled, but seems like the settings in the yalm are not disabling the cpu or gpu info in this mode.

**Comment by TheRouletteBoi** [comment]
Updated sprx file in [fps-counter-2.6](https://github.com/TheRouletteBoi/RouLetteVshMenu/releases/tag/fps-counter-2.6)
