### ISSUE TITLE
temperatureType is always shown in BOTH.

### ISSUE THREAD

**Issue by aldostools** [TheRouletteBoi/RouLetteVshMenu#26]
Issue reported in https://github.com/aldostools/webMAN-MOD/issues/713

**Comment by TheRouletteBoi** [comment]
wow I'm a rookie for creating this bug 😂

**Comment by TheRouletteBoi** [comment]
qiuck fix
https://gofile.io/d/htRdDh

**Comment by aldostools** [comment]
Thank you!

**Comment by aldostools** [comment]
Still the same issue after the update.

**Comment by TheRouletteBoi** [comment]
> Still the same issue after the update.

I tested on my side and it is working when I use `temperatureType: CELSIUS`

**Comment by aldostools** [comment]
It was my mistake. I had Cobra debug enabled. So it was loading the old version

It's working fine. Sorry for the wrong report.

**Comment by TheRouletteBoi** [comment]
In that case excellent. By the way how to you detect a debug version of Cobra?

**Comment by aldostools** [comment]
Currently I only do the check Evilnat's CFW
`#define isCobraDebug	(file_size("/dev_flash/sys/stage2.bin") > 124000)`

It's not the best way, but it works.

**Comment by TheRouletteBoi** [comment]
your methods of achieving the end goal are not always the best but as long as it works 😊

**Comment by aldostools** [comment]
LOL I know I do a lot of hacky things.
