### ISSUE TITLE
FPS Counter Identifies the hen version "wrong"

### ISSUE THREAD

**Issue by NicoBren** [TheRouletteBoi/RouLetteVshMenu#27]
![Screenshot 2022-05-31 22-35-54](https://user-images.githubusercontent.com/89282630/171311559-fbb50aea-73ce-408a-b410-a48a714608e7.png)

**Comment by TheRouletteBoi** [comment]
this is intended behavior

**Comment by TheRouletteBoi** [comment]
> > this is intended behavior
> 
> It's showing 3.11 instead of 3.1.1, webMAN MOD also had this "bug" but aldo already fixed it.

is it okay if I show cobra version 8.3.0 instead of 8.30 ?
