### ISSUE TITLE
Console Shuts down

### ISSUE THREAD

**Issue by Szipi** [TheRouletteBoi/RouLetteVshMenu#28]
Consoles: CECHH04, CECHG04 EvilNAT 4.89CFW + webMAN MOD 1.47.41
Here is what happens on both consoles:
Console starts up alright and works flawlessly.
But after activating fps counter everything shows as it should except cpu/gpu clocks are missing. After ~17 seconds YLOD, console shuts down power led red flashing and beeping. It doesn't matter what I do, browse in XMB, start a game, do nothing, it always happens at ~17 seconds.
Powering the console up again, hdd checking("the unit was not properly shut down the last time is was used") and after that the xmb starts up.
And here is the difference, after activating the fps counter again (L3+R3) everything happens as before except after ~17 seconds the cpu/gpu clocks appear too. No crash.
After shutting down the console and powering up again next day everything happens again from start.
It's like the cpu/gpu clock speed readout crashes the console.
I tried configuring the plugin to only show fps/cpu/gpu temperature/fan speed, but crashed again. It works only after a YLOD/hdd check. I checked the hdd its flawles in both consoles.
Reinstalled cfw, no luck.
I tried version 2.2 and it works flawlessly, it only freezes sometimes when exiting a game, but its a known bug.

**Comment by TheRouletteBoi** [comment]
Do you use COBRA or MAMBA payload?

**Comment by Szipi** [comment]
I don't know, evilnat cfw comes with cobra 8.3. I don't set anything like that just install webman mod and set the fan speed. I tought at first the console is bad, but the other one does the same. At psx-place.com in the webman mod topic another user had this issue like me.

**Comment by TheRouletteBoi** [comment]
Both of you mentioned you have a phat ps3 model.

From PSX PLACE

PostalDude__
Member
Joined:Jan 12, 2021
Messages:32
Trophy Points:32
the new FPS plugin and start navigating menus within the XMB, it will eventually YLOD the console with 1601/1701 (enabling the start+select menu speeds up this too). I have no clue if that has been reported so far. I have confirmed this to occur on both of my COK-001 based consoles to rule out the possibility of a hardware issue.

I have only tested on evilnat 4.88.2 so i have no clue if this occurs on any other firmware, i have uploaded a video of the issue, as well as the syscon error log if that is of any help.

The video: https://cdn.discordapp.com/attachments/888130660773003265/980949846787772536/Snapchat-265624386.mp4
and i have uploaded the syscon log the usual way
Attached Files:
[syscon log.txt](https://www.psx-place.com/threads/webman-mod-general-information-thread.9643/attachments/syscon-log-txt.37415/)
File size:1.5 KB
Views:2
PostalDude__, Tuesday at 6:17 AM

**Comment by Szipi** [comment]
I have a Slim(CECH-2004A) with EvilNAT 4.88 CFW and a super slim (CECH-4004) with HFW 4.88+HEN 3.1.
I will test it on them in the next few days.

**Comment by Szipi** [comment]
I tested the Slim.
It works, kind of. In XMB no problem, but the games freeze randomly.
I think it's maybe because of the low free memory. In XMB it is around ~1600KB, after a game starts it's only 400-500KB.
Isn't that too low?

**Comment by TheRouletteBoi** [comment]
try to lower the vsh memory used with webman plugin settings

**Comment by kostirez1** [comment]
I can confirm that this exact crash also occurs on CECHCK04 (board DIA-002).

> It's like the cpu/gpu clock speed readout crashes the console.
I tried configuring the plugin to only show fps/cpu/gpu temperature/fan speed, but crashed again.

This is indeed true, calling PeekLv1() in clock readout functions seems to be the culprit as it doesn't happen when you recompile without that call. The reason for it happening even though you disabled it in config is because still calls those functions.

Good news is this is preventable by enclosing it in an if statement. Console seems to be 100% stable after testing it for several hours. Bad news is that it doesn't fix the underlying issue, but only bypasses it. Also no clock speeds for those models, at least for now.
