### ISSUE TITLE
Feature Request: Show system time.

### ISSUE THREAD

**Issue by Alann-Mints** [TheRouletteBoi/RouLetteVshMenu#29]
Title… I think it’d be pretty handy to show the time, especially when you want to have a quick game session, but have places to be at a certain time.

**Comment by TheRouletteBoi** [comment]
like this format? `DD/MM/YY : HH/SS/MM` ? if not then what type of time are you refering to

**Comment by Alann-Mints** [comment]
Something like that would be cool. Not sure how much work this it, but maybe 24 and 12 hour could be configured in the yaml, or maybe use the format already set in PS3 settings? When the idea came to mind, I was thinking “HH:MM (am/pm)” maybe above or to one side of the FPS display. Either way, the time being there regardless of position or format would certainly be useful :)

**Comment by TheRouletteBoi** [comment]
![2022-06-10_23-33-55](https://user-images.githubusercontent.com/9206290/173176041-762c4388-5ae0-4f3c-99c4-6f8ac90a0fb7.png)

**Comment by Alann-Mints** [comment]
Thank you 😎
