### ISSUE TITLE
[Request] New Stand Alone FPS Counter Configurable .INI

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#4]
Would be nice if we can configure the new FPS counter plugin with a .ini file to remove unwanted information.

For example, to remove the Firmware Information or Ram Usage, so the user can hide/show each information overlay, would be nice too if we can set the order too.

**Comment by LuanTeles** [comment]
If possivel i would like to request if the ini file is implemented an option

Overlay: XMB or Overlay: Game and  Overlay: XMB/Game 

so the user can define if the overlay will show only on xmb, only on Game or Both

**Comment by LuanTeles** [comment]
Now that webMAN MOD includes your plugin, webMAN could also create the .INI and modify it via we commands. what do you think @Aldostools

**Comment by aldostools** [comment]
The INI is not difficult in webMAN MOD. The plugin would have to support it.

The web command /edit.ps3 could be used to edit small text files.

**Comment by LuanTeles** [comment]
> The INI is not difficult in webMAN MOD. The plugin would have to support it.
> 
> The web command /edit.ps3 could be used to edit small text files.

That's what i'm thinking about.

**Comment by TheRouletteBoi** [comment]
> Would be nice if we can configure the new FPS counter plugin with a .ini file to remove unwanted information.
> 
> For example, to remove the Firmware Information or Ram Usage, so the user can hide/show each information overlay, would be nice too if we can set the order too.

I like that idea and will consider it
