### ISSUE TITLE
[Improvement] CCAPI checks for Endstones Menus

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#40]
Can a check be added to the menus that requires CCAPI? 

Menus that require CCAPI could have explicit information in the mod's menu description that says it requires CCAPI and if the user tries to load it without CCAPI a popup could be displayed with a message that the MOD MENU cannot be activated because CCAPI is not installed on the system.

**Comment by TheRouletteBoi** [comment]
yeah that can be done. the reason why I haven't added such feature is because I have no way of detecting the CCAPI version  or rev. I can only check if ccapi.sprx file exist's

**Comment by LuanTeles** [comment]
Why it requires rev 5 or lower? Dex support?

Evilnat will release soon 4.89 DEX, maybe it could check if the system are on dex and then if ccapi.sprx is present?

**Comment by TheRouletteBoi** [comment]
rev 5 is requiered because of the ccapi syscall api used in this payloads. after rev 6 he changed it to some other api I haven't reversed engeinered. if you try to load a enstone menu after rev 5 you will get a illegal instruction segment fault which means the api was changed/ no longer supported.
