### ISSUE TITLE
[Request] Enable/Disable

### ISSUE THREAD

**Issue by ZweiBR** [TheRouletteBoi/RouLetteVshMenu#41]
I wanted to know if there is any command that disables or enables?

**Comment by TheRouletteBoi** [comment]
> I wanted to know if there is any command that disables or enables?

disables and enables what exactly?

**Comment by ZweiBR** [comment]
> 

if there is any command to disable the plugin VshFpsCounter.sprx.
Sometimes FPS, CPU, GPU etc.
It is on top of the game information, for example God of War Ascesion is on top of the character's life.

If there is any command to disable and when I want I can enable it again

**Comment by TheRouletteBoi** [comment]
> if there is any command to disable the plugin VshFpsCounter.sprx. Sometimes FPS, CPU, GPU etc. It is on top of the game information, for example God of War Ascesion is on top of the character's life.
> 
> If there is any command to disable and when I want I can enable it again

if you use webman to load VshFpsCounter.sprx simply go to `/dev_hdd0/tmp/wm_res/VshFpsCounter.yaml` open and edit the file. There you will be able to turn on and off features in plain text

**Comment by ZweiBR** [comment]
I don't use webMAN, I like something simpler.
Deank's sMAN usage

If not, no problem, your plugin is wonderful

**Comment by TheRouletteBoi** [comment]
> I don't use webMAN, I like something simpler.
> I'm using sMAN
> If it is not possible to change, no problem your plugin is wonderful

yes it's still possible you make the changes without webman. simply add the VshFpsCounter.yaml into the same directory as  [VshFpsCounter.sprx](https://github.com/TheRouletteBoi/RouLetteVshMenu/releases/tag/fps-counter-2.7)

**Comment by ZweiBR** [comment]
Perfect
thank you very much for your attention with me.

**Comment by ZweiBR** [comment]
last question is it possible to leave the temperature mode only in (*C) Celsius ?

**Comment by TheRouletteBoi** [comment]
> last question is it possible to leave the temperature mode only in (*C) Celsius ?

yes open/edit VshFpsCounter.yaml and change temperatureType to CELSIUS

**Comment by ZweiBR** [comment]
> > last question is it possible to leave the temperature mode only in (*C) Celsius ?
> 
> yes open/edit VshFpsCounter.yaml and change temperatureType to CELSIUS

thanks
