### ISSUE TITLE
Local build for VSH Menu crashed on PS3 HEN

### ISSUE THREAD

**Issue by illusion0001** [TheRouletteBoi/RouLetteVshMenu#49]
I locally built the VSH Menu on branch https://github.com/TheRouletteBoi/RouLetteVshMenu/tree/standalone-fps-counter-v2 but it crashes on my tester's PS3 HEN. works on custom firmware both using your built version and mine but on HEN, it doesn't work with my build.
Do you have any ideas? I have SDK 4.75 + VS 2013 if that matters. I tried to fix it but it didn't work.
[VshFpsCounter (2).zip](https://github.com/TheRouletteBoi/RouLetteVshMenu/files/11986059/VshFpsCounter.2.zip)

**Comment by illusion0001** [comment]
Maybe related to #47

**Comment by illusion0001** [comment]
To be more specific, the local build I posted crashes when user press L3+R3 to load it from webman, will edit this post with more info

**Comment by illusion0001** [comment]
Hm, no idea why but my local build is 89k vs the release page of 36k

**Comment by illusion0001** [comment]
Nothing else changed yet the built sprx is a lot larger.
![image](https://github.com/TheRouletteBoi/RouLetteVshMenu/assets/37698908/29ac9732-ad69-46e1-b224-5853a90934da)

**Comment by illusion0001** [comment]
It seems the sprx is compressed?

**Comment by illusion0001** [comment]
For the record I used the release binary from `Release-PS3`. It works on cfw but not hen.

**Comment by TheRouletteBoi** [comment]
> I locally built the VSH Menu on branch https://github.com/TheRouletteBoi/RouLetteVshMenu/tree/standalone-fps-counter-v2 but it crashes on my tester's PS3 HEN. works on custom firmware both using your built version and mine but on HEN, it doesn't work with my build.
> Do you have any ideas? I have SDK 4.75 + VS 2013 if that matters. I tried to fix it but it didn't work.
> [VshFpsCounter (2).zip](https://github.com/TheRouletteBoi/RouLetteVshMenu/files/11986059/VshFpsCounter.2.zip)

you need to sign the pre using 3.55 keys for the sprx to work on hen. Use TrueAncestor SELF Resigner

**Comment by illusion0001** [comment]
Thanks, `Output Method: [3.XX ALT]` works. Will open a PR to add it to the readme

**Comment by illusion0001** [comment]
Fixed in #50
