### ISSUE TITLE
[Request]  Clock Speeds

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#5]
Following the overclock patched firmwares and the ongoing xai plugin overclock on the fly, would be a nice addition to show the CPU/RAM and RSX/VRAM clock speeds.

**Comment by TheRouletteBoi** [comment]
I'm not sure how to retrive such information from kernel. Maybe @aldostools would know

**Comment by aldostools** [comment]
The clock speed is currently hardcoded in lv1.self
It would require to decrypt the hypervisor to obtain that information. It is supposed to be found decrypted in the RSX memory address, but it is unconfirmed.

**Comment by TheRouletteBoi** [comment]
> The clock speed is currently hardcoded in lv1.self
> It would require to decrypt the hypervisor to obtain that information. It is supposed to be found decrypted in the RSX memory address, but it is unconfirmed.

is RSX memory stored in LV1 or LV2?

**Comment by aldostools** [comment]
> is RSX memory stored in LV1 or LV2?

I think it's LV1, but I haven't confirmed. Check the following link;
https://www.psx-place.com/threads/project-rsx-boost-overclock-your-retail-ps3-rsx-speeds.36801/page-9#post-328447

**Comment by TheRouletteBoi** [comment]
> > is RSX memory stored in LV1 or LV2?
> 
> I think it's LV1, but I haven't confirmed. Check the following link; https://www.psx-place.com/threads/project-rsx-boost-overclock-your-retail-ps3-rsx-speeds.36801/page-9#post-328447

Aldo I found the GPU clock speed for 4.84 DEX in LV1. I'm also trying to find the CPU clock speed by searching "be.0.ref_clk" in the LV1. It would be nice if you can find these but for CEX so I can add it to the plugin.

```cpp
// rsx_dev_clock_1 + 0x1C
uint64_t m_GpuNvcSpeedOffsetInLv1 = 0x53E42C; // 4.84 DEX
   
// rsx_dev_clock_5 + 0x1C
uint64_t m_GpuDisplayClockSpeedOffsetInLv1 = 0x53E46C; // 4.84 DEX
```

**Comment by aldostools** [comment]
Here is a [dump_lv1.zip](https://github.com/TheRouletteBoi/RouLetteVshMenu/files/8495603/dump_lv1.zip) from 4.88 CEX.

Maybe it can help you to compare and find the offsets that you need.

LV1/LV2 kernel offsets in 4.84 and 4.88 should be very similar.

**Comment by TheRouletteBoi** [comment]
399 doesn't seem correct and nethier do I know the default value. Wikipedia says [3.2 GHz](https://en.wikipedia.org/wiki/PlayStation_3_technical_specifications)

**Comment by aldostools** [comment]
The most approximate value to 3.2Ghz that I found is near "be.0.nclk" at 0x3F7C
It has the value BE420E00 = 3,192,000,000

**Comment by TheRouletteBoi** [comment]
Actually if we round up to 400 then mutipliy by 8 to get GHz we get 3200.
400 MHz * 8 = 3.2 GHz

Is this resonable?

**Comment by aldostools** [comment]
It sounds forced... but it is a possibility.... I don't have experience with that info.

**Comment by TheRouletteBoi** [comment]
I don't know if this is correct but I got " * 8 for GHz" from this post. Apparently he overclocked the CPU. https://nitter.net/MinaRalwasser/status/1458862608384155650

**Comment by aldostools** [comment]
Well there are 8 processors 😄 it makes sense
