### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by urLiver** [TheRouletteBoi/RouLetteVshMenu#58]
Hello TheRouletteBoi,

I've got some Questions, which i would like to ask you.
Is it possibile to get your Discord for that matter?

Thx in advance.
Have a good Day / Night.

**Comment by TheRouletteBoi** [comment]
> Hello TheRouletteBoi,
> 
> I've got some Questions, which i would like to ask you. Is it possibile to get your Discord for that matter?
> 
> Thx in advance. Have a good Day / Night.

my discord is @therouletteboi
