### ISSUE TITLE
Show LV2 to Text is not working on my side using version 2.1

### ISSUE THREAD

**Issue by aldostools** [TheRouletteBoi/RouLetteVshMenu#6]
I poked the message "Hello World!" at the LV2 address 0x8000000000000000 using the web command:
http://0/poke.lv2?0=Hello+World!

The message does not display and the values are not cleared from memory by the plugin.

I'm using Evilnat 4.88.2 Cobra 8.30.
![image](https://user-images.githubusercontent.com/974897/162012884-46aa9689-10d2-4577-b53a-4794c6fcd60f.png)

**Comment by TheRouletteBoi** [comment]
I tested your method and also through ps3mapi and both worked. Internal code uses PS3MAPI_OPCODE_LV2_PEEK could that be an issue on CEX?


http://192.168.0.46/setmem.ps3mapi?proc=2&addr=0&val=68656C6C6F2066726F6D206B65726E656C000000
![image](https://user-images.githubusercontent.com/9206290/162063337-40f37b70-09ab-4790-a397-a7d1f7ffe2d1.png)


http://192.168.0.46/poke.lv2?0=Hello+World!
![image](https://user-images.githubusercontent.com/9206290/162063412-4c963abd-48bb-4797-84e3-05aa5bda84bf.png)

**Comment by aldostools** [comment]
Thank you for your reply. I wonder if you uploaded a version 2.1 without the LV2 to text. The Celcius / Fahrenheit is showing fine.

**Comment by TheRouletteBoi** [comment]
I actually tested this with the VshFpsCounter sprx you provided with the lastest wMM

**Comment by aldostools** [comment]
OK. Could you test on CEX?

**Comment by TheRouletteBoi** [comment]
It is not working on CEX. Something is resetting the bytes to 00 00 00 00 @ 0x8000000000000000 I even tried to remove the reset code in the sprx and somehow it is still getting reset.

**Comment by aldostools** [comment]
Could you try reading from a different address?

**Comment by TheRouletteBoi** [comment]
I've changed the offset from 0x8000000000000000 to 0x8000000000700000 this seems to work on both CEX and DEX. This could be bad if LV2 allocates to that offset or boot_plugins_kernel payload decided to allocate to that offset. I will say this method should be used as just a concep.
We should definitely create a cobra opcode with ps3mapi and let xai_plugin handle it as a vsh notfication what do you think? 

Test this sprx and report back
https://gofile.io/d/QkDpRE

**Comment by aldostools** [comment]
I tested your new plugin and for some reason it still doesn't show the text.

Maybe the issue is the method that you use to peek the value. Could you use syscall 6 (peek lv2) intead of peek lv2 through ps3mapi?

If check the memory the poked value is not removed by the plugin.
![image](https://user-images.githubusercontent.com/974897/162085372-b79ad3cc-1c31-43dc-8569-b0263147d1b4.png)

I don't think xai would be a solution, since I'm looking for a persistent overlay message to show the progress of the content scanning, dumping %, copy progress, etc.

**Comment by TheRouletteBoi** [comment]
Well I used peek from ps3mapi because of my hen console which I did the tests on.

On my end both this one and previous one are confirmed working.
This one is using syscall 6
 https://gofile.io/d/ShbNtL

By the way the message is cleared by the plugin after 5 seconds

**Comment by aldostools** [comment]
Now it's working 😄 THANK YOU!!! ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by aldostools** [comment]
The message clearing is cool as it is now, but I think it is working as regular popup.

I was looking for something that show the poked value in real time until it is removed by the homebrew. So if I poke 100 messages in minute (e.g. during a copy progress), it display at least 10 or 20 messages (depending of the poll rate that you use).

The idea is to have a "label" not a "msgbox" :-)

**Comment by aldostools** [comment]
Probably the original address 0x8000000000000000 works with syscall 6

**Comment by TheRouletteBoi** [comment]
> Probably the original address 0x8000000000000000 works with syscall 6

will syscall 6 work on hen though?

**Comment by aldostools** [comment]
Ahhh I'm not sure... I don't use HEN. I was thinking in using the address also in-game.

**Comment by TheRouletteBoi** [comment]
is there a reason why your PS3MAPI_OPCODE_LV2_PEEK isn't working?

**Comment by aldostools** [comment]
On Cobra or HEN?

**Comment by TheRouletteBoi** [comment]
On Cobra and HEN. I tried it on cobra 8.3 and HEN 3.0.3 and both worked fine for me.

**Comment by aldostools** [comment]
I was using syscall 6 in my test. I only use PS3MAPI opcode if syscalls are disabled.

**Comment by TheRouletteBoi** [comment]
So should I revert back to PS3MAPI_OPCODE_LV2_PEEK for compatability since you had syscalls disabled?

**Comment by aldostools** [comment]
What I understood is that it worked when you used syscall 6 (lv2 peek).

**Comment by TheRouletteBoi** [comment]
for me it had always worked no matter the peek syscall. but for you it only started working with syscall 6

**Comment by aldostools** [comment]
I only used syscall 7 (lv2 poke). Maybe the ps3mapi opcode in the payload is peeking in a wrong address.

**Comment by TheRouletteBoi** [comment]
This version has persistence until message is cleared by the user. 
https://gofile.io/d/kwUUqG

**Comment by aldostools** [comment]
> This version has persistence until message is cleared by the user. https://gofile.io/d/kwUUqG

Perfect!! 😀

**Comment by LouisGarry** [comment]
> This version has persistence until message is cleared by the user. https://gofile.io/d/kwUUqG

Hi master, this 2.1 version can "Quit Game" PSN PS3 normally.
Only when "Disable CFW" appears 1 Chinese character at the top right of the screen and all games don't work.

I'm using HEN 3.0.3

Thanks.

**Comment by LouisGarry** [comment]
> > This version has persistence until message is cleared by the user. https://gofile.io/d/kwUUqG
> 
> Hi master, this 2.1 version can "Quit Game" PSN PS3 normally. Only when "Disable CFW" appears 1 Chinese character at the top right of the screen and all games don't work.
> 
> I'm using HEN 3.0.3
> 
> Thanks.

And reboot or turn off seems abnormal, triple beeps.

Thanks.
