### ISSUE TITLE
[BUG] Temperatures not switching between celsius and fahrenheit while in-game

### ISSUE THREAD

**Issue by LuanTeles** [TheRouletteBoi/RouLetteVshMenu#7]
Temperature switches between celsius and fahrenheit fine on xmb, but in game it's stuck in fahrenheit mode.

**Comment by TheRouletteBoi** [comment]
This issue has been fixed in commit https://github.com/TheRouletteBoi/RouLetteVshMenu/commit/e509b3550fe44851bdee3bae7dab09f168e7a8ff
