### ISSUE TITLE
VshFpsCounter.sprx Version 2.2 makes the game unable to quit normally if  CFW syscall are disabled.

### ISSUE THREAD

**Issue by LouisGarry** [TheRouletteBoi/RouLetteVshMenu#9]
Hello master, just tried version 2.2, if CFW syscall is disabled, "Quit Game" makes PS3 hang.

Thanks.

Edited: sometimes without disabling CFW syscall "Quit Game" also hangs.
I'm use HEN 3.0.3

**Comment by TheRouletteBoi** [comment]
does this also happen when you use akari plugin?

**Comment by LouisGarry** [comment]
Thanks for your feedback.
yes, not happening using Akari 111, sometimes only loading when select game from wMM.
 I like VshFpsCounter because it shows the app (Game Title and ID).

**Comment by LouisGarry** [comment]
Thank you master
